### ISSUE TITLE
get

### ISSUE THREAD

**Issue by superhyn** [gcacace/android-signaturepad#114]

**Comment by superhyn** [comment]
i have two activities ,and each one have a signaturepad.when i jump to the second activity from the first one,there is a crash. the exception is in the title.what cofuse me is that when the targetsdk is 22(5.0),it is ok,but when i use 25,then crash. i find that if i delete onSaveInstanceState() and  onRestoreInstanceState(),it will be fine under sdkversion 25,how can i solve this issue certainly。

**Comment by superhyn** [comment]
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 6425000 bytes
                                                                   at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4039)
                                                                   at android.os.Handler.handleCallback(Handler.java:761)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:156)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                Caused by: android.os.TransactionTooLargeException: data parcel size 6425000 bytes
                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                   at android.os.BinderProxy.transact(Binder.java:617)
                                                                   at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3632)
                                                                   at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4031)
                                                                   at android.os.Handler.handleCallback(Handler.java:761) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                   at android.os.Looper.loop(Looper.java:156) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                                   at java.lang.reflect.Method.invoke(Native Method)

**Comment by pallavirichhariya22** [comment]
can u explain bit deep ur solution.

**Comment by wang0168** [comment]
> can u explain bit deep ur solution.
just like this,do not save bitmap on onSaveInstanceState() 


//    @Override
//    protected Parcelable onSaveInstanceState() {
//        Bundle bundle = new Bundle();
//        bundle.putParcelable("superState", super.onSaveInstanceState());
//        if(this.mHasEditState == null || this.mHasEditState){
//            this.mBitmapSavedState = this.getTransparentSignatureBitmap();
//        }
//        bundle.putParcelable("signatureBitmap", this.mBitmapSavedState);
//        return bundle;
//    }

**Comment by byencho** [comment]
This problem is discussed in depth [here](https://stackoverflow.com/a/44738411/5635880). Looking at the code, `SignaturePad` absolutely shouldn't be saving `mBitmapSavedState` in a `onSaveInstanceState`. Bitmaps are too large to safely store that way. [Bridge](https://github.com/livefront/bridge) is a way to solve this kind of problem in Activities and Fragments. It doesn't technically support saving state in Views out of the box (though we're looking into it) but with a little effort it could work to fix this problem.

**Comment by maxpinto** [comment]
Any fix to this issue?, i have the same exception. Absolutely the bitmap should not be saved in a bundle.

I do not want to create my own library, just for this issue, it should be applied directly in this one.

P.D. thanks for the library, and for applying databinding.

**Comment by byencho** [comment]
I can at least note that [Bridge](https://github.com/livefront/bridge) has been updated to support state saving in Views now, so that's a _potential_ option here.

**Comment by maxpinto** [comment]
Instead of using Bridge, this is how we handle this:

(We are using databinging  + viewmodel pattern)

So, our fragment is something like this:

`public class SignatureFragment extends Fragment {
     private SignatureFragmentLayoutBinding dataBinding;
     private SignatureViewModel viewModel;

     @Override
     public void onSaveInstanceState(@NonNull Bundle outState) {
          super.onSaveInstanceState(outState);
          if(viewModel != null && dataBinding != null && dataBinding.signaturePad != null){
               viewModel.setSignatureBitmap(dataBinding.signaturePad.getSignatureBitmap());
          }
     }
}`

In the onSaveInstanceState will save the signature inside the viewModel.

The viewModel is like:

`public class SignatureViewModel extends ViewModel {

    private MutableLiveData<Bitmap> signatureBitmap = new MutableLiveData<>();

    public SignatureViewModel(){ }

    public void setSignatureBitmap(Bitmap bm){
        signatureBitmap.setValue(bm);
    }
    public MutableLiveData<Bitmap> getSignatureBitmap(){
        return signatureBitmap;
    }
}`

Well the layout is like this:

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>
        <import type="android.view.View" />
        <variable
            name="viewmodel"
            type=".SignatureViewModel" />
    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            app:layout_constraintTop_toTopOf="parent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:minHeight="?attr/actionBarSize"
            android:background="@drawable/actionbar_bg"
            android:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            android:subtitleTextColor="@color/black"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            android:titleTextColor="@color/black"/>


        <package.SignaturePadView
            android:id="@+id/signature_pad"
            app:layout_constraintTop_toBottomOf="@id/toolbar"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintBottom_toTopOf="@+id/controlsPad"
            android:layout_height="0dp"
            android:layout_width="0dp"
            android:focusedByDefault="true"
            app:layout_constraintVertical_weight="3"/>

    </androidx.constraintlayout.widget.ConstraintLayout>

</layout>`


And of course the copy of the signaturePadView:

`public class SignaturePadView extends View {
     //View state
     private List<TimedPoint> mPoints;
     private boolean mIsEmpty;
     private Boolean mHasEditState;
     private float mLastTouchX;
     private float mLastTouchY;
     private float mLastVelocity;
     private float mLastWidth;
     private RectF mDirtyRect;
     private Bitmap mBitmapSavedState;

     private final SvgBuilder mSvgBuilder = new SvgBuilder();

     // Cache
     private List<TimedPoint> mPointsCache = new ArrayList<>();
     private ControlTimedPoints mControlTimedPointsCached = new ControlTimedPoints();
     private Bezier mBezierCached = new Bezier();

     //Configurable parameters
     private int mMinWidth;
     private int mMaxWidth;
     private float mVelocityFilterWeight;
     private OnSignedListener mOnSignedListener;
     private boolean mClearOnDoubleClick;

     //Click values
     private long mFirstClick;
     private int mCountClick;
     private static final int DOUBLE_CLICK_DELAY_MS = 200;

     //Default attribute values
     private final int DEFAULT_ATTR_PEN_MIN_WIDTH_PX = 3;
     private final int DEFAULT_ATTR_PEN_MAX_WIDTH_PX = 7;
     private final int DEFAULT_ATTR_PEN_COLOR = Color.BLACK;
     private final float DEFAULT_ATTR_VELOCITY_FILTER_WEIGHT = 0.9f;
     private final boolean DEFAULT_ATTR_CLEAR_ON_DOUBLE_CLICK = false;

     private Paint mPaint = new Paint();
     private Bitmap mSignatureBitmap = null;
     private Canvas mSignatureBitmapCanvas = null;

     private SignatureViewModel viewModel;

     public SignaturePadView(Context context, AttributeSet attrs) {
          super(context, attrs);
          TypedArray a = context.getTheme().obtainStyledAttributes(
               attrs,
               R.styleable.SignaturePad,
               0, 0);

          //Configurable parameters
          try {
               mMinWidth = a.getDimensionPixelSize(R.styleable.SignaturePad_penMinWidth, convertDpToPx(DEFAULT_ATTR_PEN_MIN_WIDTH_PX));
               mMaxWidth = a.getDimensionPixelSize(R.styleable.SignaturePad_penMaxWidth, convertDpToPx(DEFAULT_ATTR_PEN_MAX_WIDTH_PX));
               mPaint.setColor(a.getColor(R.styleable.SignaturePad_penColor, DEFAULT_ATTR_PEN_COLOR));
               mVelocityFilterWeight = a.getFloat(R.styleable.SignaturePad_velocityFilterWeight, DEFAULT_ATTR_VELOCITY_FILTER_WEIGHT);
               mClearOnDoubleClick = a.getBoolean(R.styleable.SignaturePad_clearOnDoubleClick, DEFAULT_ATTR_CLEAR_ON_DOUBLE_CLICK);
          } finally {
               a.recycle();
          }

          //Fixed parameters
          mPaint.setAntiAlias(true);
          mPaint.setStyle(Paint.Style.STROKE);
          mPaint.setStrokeCap(Paint.Cap.ROUND);
          mPaint.setStrokeJoin(Paint.Join.ROUND);

          //Dirty rectangle to update only the changed portion of the view
          mDirtyRect = new RectF();

          clearView();

     }

     /**
      * Set the pen color from a given resource.
      * If the resource is not found, {@link android.graphics.Color#BLACK} is assumed.
      *
      * @param colorRes the color resource.
      */
     public void setPenColorRes(int colorRes) {
          try {
               setPenColor(getResources().getColor(colorRes));
          } catch (Resources.NotFoundException ex) {
               setPenColor(Color.parseColor("#000000"));
          }
     }

     /**
      * Set the pen color from a given color.
      *
      * @param color the color.
      */
     public void setPenColor(int color) {
          mPaint.setColor(color);
     }

     /**
      * Set the minimum width of the stroke in pixel.
      *
      * @param minWidth the width in dp.
      */
     public void setMinWidth(float minWidth) {
          mMinWidth = convertDpToPx(minWidth);
     }

     /**
      * Set the maximum width of the stroke in pixel.
      *
      * @param maxWidth the width in dp.
      */
     public void setMaxWidth(float maxWidth) {
          mMaxWidth = convertDpToPx(maxWidth);
     }

     /**
      * Set the velocity filter weight.
      *
      * @param velocityFilterWeight the weight.
      */
     public void setVelocityFilterWeight(float velocityFilterWeight) {
          mVelocityFilterWeight = velocityFilterWeight;
     }

     public void clearView() {
          mSvgBuilder.clear();
          mPoints = new ArrayList<>();
          mLastVelocity = 0;
          mLastWidth = (mMinWidth + mMaxWidth) / 2;

          if (mSignatureBitmap != null) {
               mSignatureBitmap = null;
               ensureSignatureBitmap();
          }

          setIsEmpty(true);

          invalidate();
     }

     public void clear() {
          this.clearView();
          this.mHasEditState = true;
     }

     @Override
     public boolean onTouchEvent(MotionEvent event) {
          if (!isEnabled())
               return false;

          float eventX = event.getX();
          float eventY = event.getY();

          switch (event.getAction()) {
               case MotionEvent.ACTION_DOWN:
                    getParent().requestDisallowInterceptTouchEvent(true);
                    mPoints.clear();
                    if (isDoubleClick()) break;
                    mLastTouchX = eventX;
                    mLastTouchY = eventY;
                    addPoint(getNewPoint(eventX, eventY));
                    if (mOnSignedListener != null) mOnSignedListener.onStartSigning();

               case MotionEvent.ACTION_MOVE:
                    resetDirtyRect(eventX, eventY);
                    addPoint(getNewPoint(eventX, eventY));
                    setIsEmpty(false);
                    break;

               case MotionEvent.ACTION_UP:
                    resetDirtyRect(eventX, eventY);
                    addPoint(getNewPoint(eventX, eventY));
                    getParent().requestDisallowInterceptTouchEvent(true);
                    break;

               default:
                    return false;
          }

          //invalidate();
          invalidate(
               (int) (mDirtyRect.left - mMaxWidth),
               (int) (mDirtyRect.top - mMaxWidth),
               (int) (mDirtyRect.right + mMaxWidth),
               (int) (mDirtyRect.bottom + mMaxWidth));

          return true;
     }

     @Override
     protected void onDraw(Canvas canvas) {
          if (mSignatureBitmap != null) {
               canvas.drawBitmap(mSignatureBitmap, 0, 0, mPaint);
          }
     }

     public void setOnSignedListener(OnSignedListener listener) {
          mOnSignedListener = listener;
     }

     public boolean isEmpty() {
          return mIsEmpty;
     }

     public String getSignatureSvg() {
          int width = getTransparentSignatureBitmap().getWidth();
          int height = getTransparentSignatureBitmap().getHeight();
          return mSvgBuilder.build(width, height);
     }

     public Bitmap getSignatureBitmap() {
          Bitmap originalBitmap = getTransparentSignatureBitmap();
          Bitmap whiteBgBitmap = Bitmap.createBitmap(originalBitmap.getWidth(), originalBitmap.getHeight(), Bitmap.Config.ARGB_8888);
          Canvas canvas = new Canvas(whiteBgBitmap);
          canvas.drawColor(Color.WHITE);
          canvas.drawBitmap(originalBitmap, 0, 0, null);
          return whiteBgBitmap;
     }

     public void setSignatureBitmap(final Bitmap signature) {
          // View was laid out...
          if (ViewCompat.isLaidOut(this)) {
               clearView();
               ensureSignatureBitmap();

               RectF tempSrc = new RectF();
               RectF tempDst = new RectF();

               int dWidth = signature.getWidth();
               int dHeight = signature.getHeight();
               int vWidth = getWidth();
               int vHeight = getHeight();

               // Generate the required transform.
               tempSrc.set(0, 0, dWidth, dHeight);
               tempDst.set(0, 0, vWidth, vHeight);

               Matrix drawMatrix = new Matrix();
               drawMatrix.setRectToRect(tempSrc, tempDst, Matrix.ScaleToFit.CENTER);

               Canvas canvas = new Canvas(mSignatureBitmap);
               canvas.drawBitmap(signature, drawMatrix, null);
               setIsEmpty(false);
               invalidate();
          }
          // View not laid out yet e.g. called from onCreate(), onRestoreInstanceState()...
          else {
               getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                         // Remove layout listener...
                         ViewTreeObserverCompat.removeOnGlobalLayoutListener(getViewTreeObserver(), this);

                         // Signature bitmap...
                         setSignatureBitmap(signature);
                    }
               });
          }
     }

     public Bitmap getTransparentSignatureBitmap() {
          ensureSignatureBitmap();
          return mSignatureBitmap;
     }

     public Bitmap getTransparentSignatureBitmap(boolean trimBlankSpace) {

          if (!trimBlankSpace) {
               return getTransparentSignatureBitmap();
          }

          ensureSignatureBitmap();

          int imgHeight = mSignatureBitmap.getHeight();
          int imgWidth = mSignatureBitmap.getWidth();

          int backgroundColor = Color.TRANSPARENT;

          int xMin = Integer.MAX_VALUE,
               xMax = Integer.MIN_VALUE,
               yMin = Integer.MAX_VALUE,
               yMax = Integer.MIN_VALUE;

          boolean foundPixel = false;

          // Find xMin
          for (int x = 0; x < imgWidth; x++) {
               boolean stop = false;
               for (int y = 0; y < imgHeight; y++) {
                    if (mSignatureBitmap.getPixel(x, y) != backgroundColor) {
                         xMin = x;
                         stop = true;
                         foundPixel = true;
                         break;
                    }
               }
               if (stop)
                    break;
          }

          // Image is empty...
          if (!foundPixel)
               return null;

          // Find yMin
          for (int y = 0; y < imgHeight; y++) {
               boolean stop = false;
               for (int x = xMin; x < imgWidth; x++) {
                    if (mSignatureBitmap.getPixel(x, y) != backgroundColor) {
                         yMin = y;
                         stop = true;
                         break;
                    }
               }
               if (stop)
                    break;
          }

          // Find xMax
          for (int x = imgWidth - 1; x >= xMin; x--) {
               boolean stop = false;
               for (int y = yMin; y < imgHeight; y++) {
                    if (mSignatureBitmap.getPixel(x, y) != backgroundColor) {
                         xMax = x;
                         stop = true;
                         break;
                    }
               }
               if (stop)
                    break;
          }

          // Find yMax
          for (int y = imgHeight - 1; y >= yMin; y--) {
               boolean stop = false;
               for (int x = xMin; x <= xMax; x++) {
                    if (mSignatureBitmap.getPixel(x, y) != backgroundColor) {
                         yMax = y;
                         stop = true;
                         break;
                    }
               }
               if (stop)
                    break;
          }

          return Bitmap.createBitmap(mSignatureBitmap, xMin, yMin, xMax - xMin, yMax - yMin);
     }

     private boolean isDoubleClick() {
          if (mClearOnDoubleClick) {
               if (mFirstClick != 0 && System.currentTimeMillis() - mFirstClick > DOUBLE_CLICK_DELAY_MS) {
                    mCountClick = 0;
               }
               mCountClick++;
               if (mCountClick == 1) {
                    mFirstClick = System.currentTimeMillis();
               } else if (mCountClick == 2) {
                    long lastClick = System.currentTimeMillis();
                    if (lastClick - mFirstClick < DOUBLE_CLICK_DELAY_MS) {
                         this.clearView();
                         return true;
                    }
               }
          }
          return false;
     }

     private TimedPoint getNewPoint(float x, float y) {
          int mCacheSize = mPointsCache.size();
          TimedPoint timedPoint;
          if (mCacheSize == 0) {
               // Cache is empty, create a new point
               timedPoint = new TimedPoint();
          } else {
               // Get point from cache
               timedPoint = mPointsCache.remove(mCacheSize - 1);
          }

          return timedPoint.set(x, y);
     }

     private void recyclePoint(TimedPoint point) {
          mPointsCache.add(point);
     }

     private void addPoint(TimedPoint newPoint) {
          mPoints.add(newPoint);

          int pointsCount = mPoints.size();
          if (pointsCount > 3) {

               ControlTimedPoints tmp = calculateCurveControlPoints(mPoints.get(0), mPoints.get(1), mPoints.get(2));
               TimedPoint c2 = tmp.c2;
               recyclePoint(tmp.c1);

               tmp = calculateCurveControlPoints(mPoints.get(1), mPoints.get(2), mPoints.get(3));
               TimedPoint c3 = tmp.c1;
               recyclePoint(tmp.c2);

               Bezier curve = mBezierCached.set(mPoints.get(1), c2, c3, mPoints.get(2));

               TimedPoint startPoint = curve.startPoint;
               TimedPoint endPoint = curve.endPoint;

               float velocity = endPoint.velocityFrom(startPoint);
               velocity = Float.isNaN(velocity) ? 0.0f : velocity;

               velocity = mVelocityFilterWeight * velocity
                    + (1 - mVelocityFilterWeight) * mLastVelocity;

               // The new width is a function of the velocity. Higher velocities
               // correspond to thinner strokes.
               float newWidth = strokeWidth(velocity);

               // The Bezier's width starts out as last curve's final width, and
               // gradually changes to the stroke width just calculated. The new
               // width calculation is based on the velocity between the Bezier's
               // start and end mPoints.
               addBezier(curve, mLastWidth, newWidth);

               mLastVelocity = velocity;
               mLastWidth = newWidth;

               // Remove the first element from the list,
               // so that we always have no more than 4 mPoints in mPoints array.
               recyclePoint(mPoints.remove(0));

               recyclePoint(c2);
               recyclePoint(c3);

          } else if (pointsCount == 1) {
               // To reduce the initial lag make it work with 3 mPoints
               // by duplicating the first point
               TimedPoint firstPoint = mPoints.get(0);
               mPoints.add(getNewPoint(firstPoint.x, firstPoint.y));
          }
          this.mHasEditState = true;
     }

     private void addBezier(Bezier curve, float startWidth, float endWidth) {
          mSvgBuilder.append(curve, (startWidth + endWidth) / 2);
          ensureSignatureBitmap();
          float originalWidth = mPaint.getStrokeWidth();
          float widthDelta = endWidth - startWidth;
          float drawSteps = (float) Math.ceil(curve.length());

          for (int i = 0; i < drawSteps; i++) {
               // Calculate the Bezier (x, y) coordinate for this step.
               float t = ((float) i) / drawSteps;
               float tt = t * t;
               float ttt = tt * t;
               float u = 1 - t;
               float uu = u * u;
               float uuu = uu * u;

               float x = uuu * curve.startPoint.x;
               x += 3 * uu * t * curve.control1.x;
               x += 3 * u * tt * curve.control2.x;
               x += ttt * curve.endPoint.x;

               float y = uuu * curve.startPoint.y;
               y += 3 * uu * t * curve.control1.y;
               y += 3 * u * tt * curve.control2.y;
               y += ttt * curve.endPoint.y;

               // Set the incremental stroke width and draw.
               mPaint.setStrokeWidth(startWidth + ttt * widthDelta);
               mSignatureBitmapCanvas.drawPoint(x, y, mPaint);
               expandDirtyRect(x, y);
          }

          mPaint.setStrokeWidth(originalWidth);
     }

     private ControlTimedPoints calculateCurveControlPoints(TimedPoint s1, TimedPoint s2, TimedPoint s3) {
          float dx1 = s1.x - s2.x;
          float dy1 = s1.y - s2.y;
          float dx2 = s2.x - s3.x;
          float dy2 = s2.y - s3.y;

          float m1X = (s1.x + s2.x) / 2.0f;
          float m1Y = (s1.y + s2.y) / 2.0f;
          float m2X = (s2.x + s3.x) / 2.0f;
          float m2Y = (s2.y + s3.y) / 2.0f;

          float l1 = (float) Math.sqrt(dx1 * dx1 + dy1 * dy1);
          float l2 = (float) Math.sqrt(dx2 * dx2 + dy2 * dy2);

          float dxm = (m1X - m2X);
          float dym = (m1Y - m2Y);
          float k = l2 / (l1 + l2);
          if (Float.isNaN(k)) k = 0.0f;
          float cmX = m2X + dxm * k;
          float cmY = m2Y + dym * k;

          float tx = s2.x - cmX;
          float ty = s2.y - cmY;

          return mControlTimedPointsCached.set(getNewPoint(m1X + tx, m1Y + ty), getNewPoint(m2X + tx, m2Y + ty));
     }

     private float strokeWidth(float velocity) {
          return Math.max(mMaxWidth / (velocity + 1), mMinWidth);
     }

     /**
      * Called when replaying history to ensure the dirty region includes all
      * mPoints.
      *
      * @param historicalX the previous x coordinate.
      * @param historicalY the previous y coordinate.
      */
     private void expandDirtyRect(float historicalX, float historicalY) {
          if (historicalX < mDirtyRect.left) {
               mDirtyRect.left = historicalX;
          } else if (historicalX > mDirtyRect.right) {
               mDirtyRect.right = historicalX;
          }
          if (historicalY < mDirtyRect.top) {
               mDirtyRect.top = historicalY;
          } else if (historicalY > mDirtyRect.bottom) {
               mDirtyRect.bottom = historicalY;
          }
     }

     /**
      * Resets the dirty region when the motion event occurs.
      *
      * @param eventX the event x coordinate.
      * @param eventY the event y coordinate.
      */
     private void resetDirtyRect(float eventX, float eventY) {

          // The mLastTouchX and mLastTouchY were set when the ACTION_DOWN motion event occurred.
          mDirtyRect.left = Math.min(mLastTouchX, eventX);
          mDirtyRect.right = Math.max(mLastTouchX, eventX);
          mDirtyRect.top = Math.min(mLastTouchY, eventY);
          mDirtyRect.bottom = Math.max(mLastTouchY, eventY);
     }

     private void setIsEmpty(boolean newValue) {
          mIsEmpty = newValue;
          if (mOnSignedListener != null) {
               if (mIsEmpty) {
                    mOnSignedListener.onClear();
               } else {
                    mOnSignedListener.onSigned();
               }
          }
     }

     private void ensureSignatureBitmap() {
          if (mSignatureBitmap == null) {
               mSignatureBitmap = Bitmap.createBitmap(getWidth(), getHeight(),
                    Bitmap.Config.ARGB_8888);
               mSignatureBitmapCanvas = new Canvas(mSignatureBitmap);
          }
     }

     private int convertDpToPx(float dp) {
          return Math.round(getContext().getResources().getDisplayMetrics().density * dp);
     }

     public interface OnSignedListener {
          void onStartSigning();

          void onSigned();

          void onClear();
     }

     public List<TimedPoint> getPoints() {
          return mPoints;
     }
}`

Of course, in this view we removed the "OnSaveInstance" and on "onRestoreInstanceState" methods.


ViewModel handle the restoring objects by default. So we only have to override the onSaveInstanceState in the Fragment Or Activity, to save changes in the viewModel.

**Comment by byencho** [comment]
@maxpinto Storing data in a `ViewModel` is only going to solve the problem for configuration changes like rotations. If you actually want the data to be available after process-death-and-restoration you need a more robust solution. You can easily test those scenarios with something like [Process Killer](https://play.google.com/store/apps/details?id=com.livefront.processkiller). There is a great article about this by [Lyla Fujiwara at Google](https://medium.com/androiddevelopers/viewmodels-persistence-onsaveinstancestate-restoring-ui-state-and-loaders-fc7cc4a6c090) . [Bridge](https://github.com/livefront/bridge) handles both rotations and process death.

**Comment by maxpinto** [comment]
@byencho you are right, but for me in the given way works for now, i am not interested in using a external library like Bridge for that cases.

**Comment by byencho** [comment]
@maxpinto Sure, that's fair. I just wanted to be clear on what the options are for handling different aspects of the problem.

**Comment by gcacace** [comment]
Thanks for raising this issue. My idea would be to change the implementation of the view to store all the TimedPoints so they can be then persisted in the Bundle for the InstanceState, then when the view is restored we can easily rebuild the bitmap based on the stored points. This to me is a much cleaner solution compared to store the whole bitmap. I'm trying to get some time to perform a progressive refactoring, but collaboration is more than welcome: if you have some time to perform this change I would be more than happy to review and release your pull request.

**Comment by PieterPicup** [comment]
@gcacace I have implemented a simple attr which can be turned off for users who are having this issue and do not need the state to be saved. My use case I clear the view on pause anyway so I do not need the saved state. Let me know if you want me to PR this.

**Comment by andreeamicu** [comment]
For anyone who wants a quick fix, adding the xml attribute **android:saveEnabled="false"** to the <com.github.gcacace.signaturepad.views.SignaturePad> element in your layout stops the onSaveInstanceState() method from being called and prevents the TransactionTooLargeException. From the android.view.View docs: "android:saveEnabled - If false, no state will be saved for this view when it is being frozen"

**Comment by fabiorbap** [comment]
@andreeamicu Thanks that solved it for me!

**Comment by kingcxsc** [comment]
> For anyone who wants a quick fix, adding the xml attribute **android:saveEnabled="false"** to the <com.github.gcacace.signaturepad.views.SignaturePad> element in your layout stops the onSaveInstanceState() method from being called and prevents the TransactionTooLargeException. From the android.view.View docs: "android:saveEnabled - If false, no state will be saved for this view when it is being frozen"

Simply Effective

**Comment by MishraJI** [comment]
The click is consider as signature
Please check
