### ISSUE TITLE
saving instance state may throw due to zero bounds

### ISSUE THREAD

**Issue by masc3d** [gcacace/android-signaturepad#145]
on rare occasions 
```ERROR - Uncaught exception [Thread[main,5,main]] width and height must be > 0
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
        at com.github.gcacace.signaturepad.views.SignaturePad.d()
        at com.github.gcacace.signaturepad.views.SignaturePad.getTransparentSignatureBitmap()
        at com.github.gcacace.signaturepad.views.SignaturePad.onSaveInstanceState()
```

**Comment by MrFuFuFu** [comment]
Having the same issue when the view Visibility is GONE and close the fragment will crash.

**Comment by assaneonline** [comment]
Any idea how to mitigate this ?

**Comment by masc3d** [comment]
as long as this is not merged, you could use `com.github.masc3d:android-signaturepad:b60f117e` instead.
requires jitpack repository `maven { url 'https://jitpack.io' }`

**Comment by warting** [comment]
@masc3d  @assaneonline Hey! This project seems to be stale and not updated any more, I have solved this and many other stuff here if you are interested: https://github.com/warting/android-signaturepad

**Comment by Tgo1014** [comment]
Any news about merging this PR?

**Comment by achall9** [comment]
I saw this PR is merged, but not showing on v1.3.1 when import using gradle?

**Comment by tristanlarsin** [comment]
I am also encountering this issue on `v1.3.1`. @masc3d What is the status of the fix?

**Comment by padideh** [comment]
i have same issue , is this issue fixed?

**Comment by tristanlarsin** [comment]
Here's a temporary fix I did to prevent this - Add `android:saveEnabled="false"` to the xml layout 

```
<com.github.gcacace.signaturepad.views.SignaturePad
    android:id="@+id/signature_pad"
    android:saveEnabled="false"
    ...
    />
 ```

**Comment by danielcshn** [comment]
I'm currently experiencing this issue using Fragments; previously, I didn't have the problem in a test Activity. The solution from [tristanlarsin](https://github.com/tristanlarsin) seems to work.
