### ISSUE TITLE
it an issue for store too large data in one bitmap

### ISSUE THREAD

**Issue by hunterrrzz** [gcacace/android-signaturepad#166]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.training.canvas_demo, PID: 22730
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2821908 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2821908 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4672)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)

//------------------Signature pad-----------------------//
         //-----------------original-----------------//
    @Override
    protected Parcelable onSaveInstanceState() {
        Bundle bundle = new Bundle();
        bundle.putParcelable("superState", super.onSaveInstanceState());
        if (this.mHasEditState == null || this.mHasEditState) {
            this.mBitmapSavedState = this.getTransparentSignatureBitmap();
        }
        bundle.putParcelable("signatureBitmap", this.mBitmapSavedState);
        return bundle;
    }
    //---------------------------to change-----------------------//
        @Override
    protected Parcelable onSaveInstanceState() {
        Bundle bundle = new Bundle();
        bundle.putParcelable("superState", super.onSaveInstanceState());
        if (this.mHasEditState == null || this.mHasEditState) {
        Bitmap mBitmapSavedState = this.getTransparentSignatureBitmap();
        }
        bundle.putParcelable("signatureBitmap", mBitmapSavedState);
        return bundle;
    }
    
    it will solve the issue

**Comment by warting** [comment]
@hunterrrzz Hey man. This project seems to be stale and not updated any more, I have solved this and many other bugs here if you are interested: https://github.com/warting/android-signaturepad

**Comment by gcacace** [comment]
Duplicate of #49
