### ISSUE TITLE
Issue while signature pad in Android 12

### ISSUE THREAD

**Issue by DineshKumarS15** [gcacace/android-signaturepad#172]
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2154)
       at android.os.Parcel.writeParcelable(Parcel.java:1965)
       at android.os.Parcel.writeValue(Parcel.java:1871)

**Comment by joshfriend** [comment]
I am seeing the same issue.

See also #171, #169, #168, #153

Full stack trace:

<details>

```
Fatal Exception: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
       at android.graphics.Bitmap.nativeWriteToParcel(Bitmap.java)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:2154)
       at android.os.Parcel.writeParcelable(Parcel.java:1965)
       at android.os.Parcel.writeValue(Parcel.java:1871)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.os.Parcel.writeBundle(Parcel.java:1105)
       at android.os.Parcel.writeValue(Parcel.java:1862)
       at android.os.Parcel.writeSparseArray(Parcel.java:1193)
       at android.os.Parcel.writeValue(Parcel.java:1896)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.os.Parcel.writeBundle(Parcel.java:1105)
       at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:161)
       at android.os.Parcel.writeTypedObject(Parcel.java:1798)
       at android.os.Parcel.writeTypedList(Parcel.java:1677)
       at android.os.Parcel.writeTypedList(Parcel.java:1634)
       at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:64)
       at android.os.Parcel.writeParcelable(Parcel.java:1965)
       at android.os.Parcel.writeValue(Parcel.java:1871)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.os.Parcel.writeBundle(Parcel.java:1105)
       at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:161)
       at android.os.Parcel.writeTypedObject(Parcel.java:1798)
       at android.os.Parcel.writeTypedList(Parcel.java:1677)
       at android.os.Parcel.writeTypedList(Parcel.java:1634)
       at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:64)
       at android.os.Parcel.writeParcelable(Parcel.java:1965)
       at android.os.Parcel.writeValue(Parcel.java:1871)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.os.Parcel.writeBundle(Parcel.java:1105)
       at android.os.Parcel.writeValue(Parcel.java:1862)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.os.Parcel.writeBundle(Parcel.java:1105)
       at android.os.Parcel.writeValue(Parcel.java:1862)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
       at android.os.Bundle.writeToParcel(Bundle.java:1304)
       at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1339)
       at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
</details>

**Comment by DineshKumarS15** [comment]
Issue fixed with downgraded the signature pad dependency version from 1.3.1 to 1.2.1

implementation "com.github.gcacace:signature-pad:1.2.1"

**Comment by prernagp** [comment]
@DineshKumarS15 it is not allowing me to downgrade the version. Is there any other way?

**Comment by juliogarcesrios** [comment]
> @DineshKumarS15 it is not allowing me to downgrade the version. Is there any other way?

android:saveEnabled="false"
