### ISSUE TITLE
Crashing when the activity goes in background on android 11, 12

### ISSUE THREAD

**Issue by ErDeepChand** [gcacace/android-signaturepad#178]
```
     java.lang.RuntimeException: Could not copy bitmap to parcel blob.
                                            	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
                                            	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2124)
                                            	at android.os.Parcel.writeParcelable(Parcel.java:1952)
                                            	at android.os.Parcel.writeValue(Parcel.java:1858)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.os.Parcel.writeBundle(Parcel.java:1092)
                                            	at android.os.Parcel.writeValue(Parcel.java:1849)
                                            	at android.os.Parcel.writeSparseArray(Parcel.java:1180)
                                            	at android.os.Parcel.writeValue(Parcel.java:1883)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.os.Parcel.writeBundle(Parcel.java:1092)
                                            	at android.os.Parcel.writeValue(Parcel.java:1849)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1278)
                                            	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
                                            	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
                                            	at android.os.Handler.handleCallback(Handler.java:938)
                                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                                            	at android.os.Looper.loopOnce(Looper.java:201)
                                            	at android.os.Looper.loop(Looper.java:288)
                                            	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                            	at java.lang.reflect.Method.invoke(Native Method)
                                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```     java.lang.RuntimeException: Could not copy bitmap to parcel blob.
                                            	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
                                            	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2124)
                                            	at android.os.Parcel.writeParcelable(Parcel.java:1952)
                                            	at android.os.Parcel.writeValue(Parcel.java:1858)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.os.Parcel.writeBundle(Parcel.java:1092)
                                            	at android.os.Parcel.writeValue(Parcel.java:1849)
                                            	at android.os.Parcel.writeSparseArray(Parcel.java:1180)
                                            	at android.os.Parcel.writeValue(Parcel.java:1883)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.os.Parcel.writeBundle(Parcel.java:1092)
                                            	at android.os.Parcel.writeValue(Parcel.java:1849)
                                            	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
                                            	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
                                            	at android.os.Bundle.writeToParcel(Bundle.java:1304)
                                            	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1278)
                                            	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
                                            	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
                                            	at android.os.Handler.handleCallback(Handler.java:938)
                                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                                            	at android.os.Looper.loopOnce(Looper.java:201)
                                            	at android.os.Looper.loop(Looper.java:288)
                                            	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                            	at java.lang.reflect.Method.invoke(Native Method)
                                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by shankar81** [comment]
same here

**Comment by rensieeee** [comment]
https://github.com/prologapp/android-signaturepad Use this fork instead, fixed the issue for me. This repo is abandoned anyway.

**Comment by sl-18500** [comment]
setSaveEnabled(false)
