### ISSUE TITLE
The signature page crashes when placed in the backend program

### ISSUE THREAD

**Issue by longkiGit** [gcacace/android-signaturepad#182]
The signature page crashes when placed in the backend program

**Comment by rensieeee** [comment]
https://github.com/prologapp/android-signaturepad Use this fork instead, fixed the issue for me. This repo is abandoned anyway.

**Comment by pleusna** [comment]
It is a great library. Has use since 1.2.1.

However, the android studio find the version 1.2.0 and 1.3.1.
The 1.2.0 have problem on final result that can not be use.

Having issue that already reported.
Please add some code to avoid the total app crash.

The crash details found in the re-creation from android activity.
It results to  

java.lang.IllegalArgumentException: width and height must be > 0
   at android.graphics.Bitmap.createBitmap(Bitmap.java:1249)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:1215)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:1163)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:1122)
   at com.github.gcacace.signaturepad.views.SignaturePad.ensureSignatureBitmap(SignaturePad.java:607)
   at com.github.gcacace.signaturepad.views.SignaturePad.getTransparentSignatureBitmap(SignaturePad.java:314)
   at com.github.gcacace.signaturepad.views.SignaturePad.onSaveInstanceState(SignaturePad.java:109)
