### ISSUE TITLE
Bitmap size exceeds 32bits

### ISSUE THREAD

**Issue by Anth06ny** [gcacace/android-signaturepad#33]
HI, I have a problem with your library, applicaiton crash on Motorolla Moto G phone.

It's work on nexus phone everytime.
But on moto G if I set fix size, it's work, but if I set match_parent, application crash : 

11-30 10:41:54.441 18324-18324/temp.com.payzenmpos.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: temp.com.payzenmpos.dev, PID: 18324
                                                                         java.lang.IllegalArgumentException: bitmap size exceeds 32bits
                                                                             at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:813)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:780)

Do you have any idea ?

**Comment by gcacace** [comment]
Refer to #49
