### ISSUE TITLE
Set Already Signed Bitmap as signature bitmap

### ISSUE THREAD

**Issue by arundaskv** [gcacace/android-signaturepad#9]
Hi i have a requirement, i need to set the already signed signature bit to the signature view, and allow user to edit or modify the signature. I couldnt do this with this library. Except this , the library is working awesome. Please provide a solution. Thanks in advance. 
my email is arundaskv@gmail.com. Its urgent for me. If you help me to find a solution, it will help a lot.

**Comment by arundaskv** [comment]
what i am trying now is 

signPad.setSignatureBitmap(bitmap); where the passig 'bitmap'  object is already saved one.
it results nothing. What i can do is make the bitmap object as the background og signPad. But it never results modifying the existing one

**Comment by abdulrahmanmajeed** [comment]
how to use setSignatureBitmap(bitmap) method as I am facing the exception with height and width must be greater than 0

**Comment by ChaitanyaDuse** [comment]
Error after setSignatureBitmap(bitmap) 
need to set existing bitmap. 

 java.lang.IllegalArgumentException: width and height must be > 0
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:855)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:801)
                                                                            at com.github.gcacace.signaturepad.views.SignaturePad.ensureSignatureBitmap(SignaturePad.java:487)
                                                                            at com.github.gcacace.signaturepad.views.SignaturePad.setSignatureBitmap(SignaturePad.java:223)
                                                                            at com.appbirds.sitechecklist.ui.adapter.MyOnSignatureClickListener.onClick(MyOnSignatureClickListener.java:94)
                                                                            at android.view.View.performClick(View.java:5201)
                                                                            at android.view.View$PerformClick.run(View.java:21163)
                                                                            at android.os.Handler.handleCallback(Handler.java:746)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by dandar3** [comment]
Hey guys,

you may be doing this before it is being laid out (view width and height are 0) - code below might help:

```
mSignaturePad.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
    public void onGlobalLayout() {
        // Remove layout listener...
        ViewTreeObserverCompat.removeOnGlobalLayoutListener(mSignaturePad.getViewTreeObserver(), this);

        // Restore bitmap...
        mSignaturePad.setSignatureBitmap(bitmap);
    }
});
```

where

```
public class ViewTreeObserverCompat {
    /**
     * @param observer
     * @param victim
     */
    @SuppressLint("NewApi")
    @SuppressWarnings("deprecation")
    public static void removeOnGlobalLayoutListener(ViewTreeObserver observer, @Nullable ViewTreeObserver.OnGlobalLayoutListener victim) {
        // Legacy (API15-)...
        if (Build.VERSION.SDK_INT <= 15) {
            observer.removeGlobalOnLayoutListener(victim);
        }
        // Future (API16+)...
        else {
            observer.removeOnGlobalLayoutListener(victim);
        }
    }
}
```

**Comment by gcacace** [comment]
@dandar3 it would be great if you could open a pull request with that change!

**Comment by dandar3** [comment]
Sorry, my first pull request here, didn't think both committs will go into into the same pull request (#55). Let me know if that is a problem for you or how I could split it on my end, thanks.
